### PR TITLE
Some Pirouette love.

### PR DESCRIPTION
**Pull request by carlosalberto**
Things to observe:

1. enums style: in Foundation lower case has been used, but in AppKit upper casing the first char is the followed style (i.e. "default" vs "Default"). Which one should we follow?

2. I added a NSObject.new() method for objects that have parameterless init() methods (say, NSNumberFormatter). Does the naming looks ok?

3. I have samples for the new UI wrappers, but I can only commit them after I have these bits in echo-js ;)

### CODE REVIEW

**Comment by toshok** [comment]
1. I *think* EnumName.enumElement is better as it's more consistent with casing elsewhere in the bindings, but clearly I've come down on either side of the argument in the past.  What do you think?

2. Naming looks good, but you aren't calling the init() method.  You'll need to massage the remainder of .newWith and c&p it over.  you can switch the `.apply(instance, newInfo.args);` to `.call(instance);`.

3. sweeeet

**Comment by carlosalberto** [comment]
1. I think Enum.enumElement is indeed more JS-esque, and also consistent with the current naming in the project. Should I change the casing for the elements in AppKit then? Or should we just keep this idea around?

2. Ooops, hadn't realized that. [NSNumberFormatter alloc] strangely works just nice for me. Will put the needed bits later today there.

**Comment by carlosalberto** [comment]
Updated the request to call NSObject.init() as needed. The only thing that remains is the enum naming. Have we decided what do to on that front yet? ;)

**Comment by toshok** [comment]
re enums, let's change to Enum.enumElement everywhere.

**Comment by carlosalberto** [comment]
Awesome, thanks!

**Pull request merged**
